version: "3.9"

services:
  frontend:
    build:
      context: .             # a raiz do compose é frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./platform_ui:/app   # sincroniza a pasta platform_ui com /app no container
    environment:
      - CHOKIDAR_USEPOLLING=true