services:
  anchor:
    build: .
    #container_name: anchor_container2
    volumes:
      - ./:/workspace
    ports:
      - "8899:8899"
      - "8900:8900"
      - "8901:8901"
    stdin_open: true
    tty: true
    command: /root/.local/share/solana/install/active_release/bin/solana-test-validator --reset