services:
  db:
    image: postgres:16
    container_name: backend-db
    environment:
      POSTGRES_USER: tomaspsaraujo
      POSTGRES_PASSWORD: 1235812
      POSTGRES_DB: mydb
    #ports:
    #  - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tomaspsaraujo -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app     # <-- host backend folder mapped directly to /app
      - ./platform_core:/app/platform_core
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: mydb
      DATABASE_USER: tomaspsaraujo
      DATABASE_PASSWORD: 1235812

volumes:
  postgres_data:
