apiVersion: v1
kind: Service
metadata:
  name: anchor-service
spec:
  selector:
    app: anchor
  type: NodePort
  ports:
    - name: rpc
      port: 8899
      targetPort: 8899
      nodePort: 30001
    - name: ws
      port: 8900
      targetPort: 8900
      nodePort: 30002
    - name: optional
      port: 8901
      targetPort: 8901
      nodePort: 30003